// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: linearpbft.proto

package org.cse535.proto;

public interface ActivateServerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ActivateServerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>string serverName = 2;</code>
   */
  java.lang.String getServerName();
  /**
   * <code>string serverName = 2;</code>
   */
  com.google.protobuf.ByteString
      getServerNameBytes();
}
