// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: linearpbft.proto

package org.cse535.proto;

public interface CommandOutputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CommandOutput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string output = 1;</code>
   */
  java.lang.String getOutput();
  /**
   * <code>string output = 1;</code>
   */
  com.google.protobuf.ByteString
      getOutputBytes();
}
