// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: linearpbft.proto

package org.cse535.proto;

/**
 * Protobuf type {@code NewViewRequest}
 */
public  final class NewViewRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:NewViewRequest)
    NewViewRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NewViewRequest.newBuilder() to construct.
  private NewViewRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NewViewRequest() {
    view_ = 0;
    processId_ = "";
    viewChangeMessages_ = java.util.Collections.emptyList();
    prepareMessages_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NewViewRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            view_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            processId_ = s;
            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (timestamp_ != null) {
              subBuilder = timestamp_.toBuilder();
            }
            timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timestamp_);
              timestamp_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              viewChangeMessages_ = new java.util.ArrayList<org.cse535.proto.ViewChangeRequest>();
              mutable_bitField0_ |= 0x00000008;
            }
            viewChangeMessages_.add(
                input.readMessage(org.cse535.proto.ViewChangeRequest.parser(), extensionRegistry));
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              prepareMessages_ = new java.util.ArrayList<org.cse535.proto.PrepareRequest>();
              mutable_bitField0_ |= 0x00000010;
            }
            prepareMessages_.add(
                input.readMessage(org.cse535.proto.PrepareRequest.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        viewChangeMessages_ = java.util.Collections.unmodifiableList(viewChangeMessages_);
      }
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        prepareMessages_ = java.util.Collections.unmodifiableList(prepareMessages_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.cse535.proto.Linearpbft.internal_static_NewViewRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.cse535.proto.Linearpbft.internal_static_NewViewRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.cse535.proto.NewViewRequest.class, org.cse535.proto.NewViewRequest.Builder.class);
  }

  private int bitField0_;
  public static final int VIEW_FIELD_NUMBER = 1;
  private int view_;
  /**
   * <code>int32 view = 1;</code>
   */
  public int getView() {
    return view_;
  }

  public static final int PROCESSID_FIELD_NUMBER = 2;
  private volatile java.lang.Object processId_;
  /**
   * <code>string processId = 2;</code>
   */
  public java.lang.String getProcessId() {
    java.lang.Object ref = processId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      processId_ = s;
      return s;
    }
  }
  /**
   * <code>string processId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getProcessIdBytes() {
    java.lang.Object ref = processId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      processId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp timestamp_;
  /**
   * <code>.google.protobuf.Timestamp timestamp = 3;</code>
   */
  public boolean hasTimestamp() {
    return timestamp_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 3;</code>
   */
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 3;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    return getTimestamp();
  }

  public static final int VIEWCHANGEMESSAGES_FIELD_NUMBER = 4;
  private java.util.List<org.cse535.proto.ViewChangeRequest> viewChangeMessages_;
  /**
   * <code>repeated .ViewChangeRequest viewChangeMessages = 4;</code>
   */
  public java.util.List<org.cse535.proto.ViewChangeRequest> getViewChangeMessagesList() {
    return viewChangeMessages_;
  }
  /**
   * <code>repeated .ViewChangeRequest viewChangeMessages = 4;</code>
   */
  public java.util.List<? extends org.cse535.proto.ViewChangeRequestOrBuilder> 
      getViewChangeMessagesOrBuilderList() {
    return viewChangeMessages_;
  }
  /**
   * <code>repeated .ViewChangeRequest viewChangeMessages = 4;</code>
   */
  public int getViewChangeMessagesCount() {
    return viewChangeMessages_.size();
  }
  /**
   * <code>repeated .ViewChangeRequest viewChangeMessages = 4;</code>
   */
  public org.cse535.proto.ViewChangeRequest getViewChangeMessages(int index) {
    return viewChangeMessages_.get(index);
  }
  /**
   * <code>repeated .ViewChangeRequest viewChangeMessages = 4;</code>
   */
  public org.cse535.proto.ViewChangeRequestOrBuilder getViewChangeMessagesOrBuilder(
      int index) {
    return viewChangeMessages_.get(index);
  }

  public static final int PREPAREMESSAGES_FIELD_NUMBER = 5;
  private java.util.List<org.cse535.proto.PrepareRequest> prepareMessages_;
  /**
   * <code>repeated .PrepareRequest prepareMessages = 5;</code>
   */
  public java.util.List<org.cse535.proto.PrepareRequest> getPrepareMessagesList() {
    return prepareMessages_;
  }
  /**
   * <code>repeated .PrepareRequest prepareMessages = 5;</code>
   */
  public java.util.List<? extends org.cse535.proto.PrepareRequestOrBuilder> 
      getPrepareMessagesOrBuilderList() {
    return prepareMessages_;
  }
  /**
   * <code>repeated .PrepareRequest prepareMessages = 5;</code>
   */
  public int getPrepareMessagesCount() {
    return prepareMessages_.size();
  }
  /**
   * <code>repeated .PrepareRequest prepareMessages = 5;</code>
   */
  public org.cse535.proto.PrepareRequest getPrepareMessages(int index) {
    return prepareMessages_.get(index);
  }
  /**
   * <code>repeated .PrepareRequest prepareMessages = 5;</code>
   */
  public org.cse535.proto.PrepareRequestOrBuilder getPrepareMessagesOrBuilder(
      int index) {
    return prepareMessages_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (view_ != 0) {
      output.writeInt32(1, view_);
    }
    if (!getProcessIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, processId_);
    }
    if (timestamp_ != null) {
      output.writeMessage(3, getTimestamp());
    }
    for (int i = 0; i < viewChangeMessages_.size(); i++) {
      output.writeMessage(4, viewChangeMessages_.get(i));
    }
    for (int i = 0; i < prepareMessages_.size(); i++) {
      output.writeMessage(5, prepareMessages_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (view_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, view_);
    }
    if (!getProcessIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, processId_);
    }
    if (timestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTimestamp());
    }
    for (int i = 0; i < viewChangeMessages_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, viewChangeMessages_.get(i));
    }
    for (int i = 0; i < prepareMessages_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, prepareMessages_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.cse535.proto.NewViewRequest)) {
      return super.equals(obj);
    }
    org.cse535.proto.NewViewRequest other = (org.cse535.proto.NewViewRequest) obj;

    boolean result = true;
    result = result && (getView()
        == other.getView());
    result = result && getProcessId()
        .equals(other.getProcessId());
    result = result && (hasTimestamp() == other.hasTimestamp());
    if (hasTimestamp()) {
      result = result && getTimestamp()
          .equals(other.getTimestamp());
    }
    result = result && getViewChangeMessagesList()
        .equals(other.getViewChangeMessagesList());
    result = result && getPrepareMessagesList()
        .equals(other.getPrepareMessagesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VIEW_FIELD_NUMBER;
    hash = (53 * hash) + getView();
    hash = (37 * hash) + PROCESSID_FIELD_NUMBER;
    hash = (53 * hash) + getProcessId().hashCode();
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    if (getViewChangeMessagesCount() > 0) {
      hash = (37 * hash) + VIEWCHANGEMESSAGES_FIELD_NUMBER;
      hash = (53 * hash) + getViewChangeMessagesList().hashCode();
    }
    if (getPrepareMessagesCount() > 0) {
      hash = (37 * hash) + PREPAREMESSAGES_FIELD_NUMBER;
      hash = (53 * hash) + getPrepareMessagesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.cse535.proto.NewViewRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.NewViewRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.NewViewRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.NewViewRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.NewViewRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.NewViewRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.NewViewRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cse535.proto.NewViewRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cse535.proto.NewViewRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.cse535.proto.NewViewRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cse535.proto.NewViewRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cse535.proto.NewViewRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.cse535.proto.NewViewRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code NewViewRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:NewViewRequest)
      org.cse535.proto.NewViewRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cse535.proto.Linearpbft.internal_static_NewViewRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cse535.proto.Linearpbft.internal_static_NewViewRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cse535.proto.NewViewRequest.class, org.cse535.proto.NewViewRequest.Builder.class);
    }

    // Construct using org.cse535.proto.NewViewRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getViewChangeMessagesFieldBuilder();
        getPrepareMessagesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      view_ = 0;

      processId_ = "";

      if (timestampBuilder_ == null) {
        timestamp_ = null;
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }
      if (viewChangeMessagesBuilder_ == null) {
        viewChangeMessages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        viewChangeMessagesBuilder_.clear();
      }
      if (prepareMessagesBuilder_ == null) {
        prepareMessages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        prepareMessagesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.cse535.proto.Linearpbft.internal_static_NewViewRequest_descriptor;
    }

    @java.lang.Override
    public org.cse535.proto.NewViewRequest getDefaultInstanceForType() {
      return org.cse535.proto.NewViewRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.cse535.proto.NewViewRequest build() {
      org.cse535.proto.NewViewRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.cse535.proto.NewViewRequest buildPartial() {
      org.cse535.proto.NewViewRequest result = new org.cse535.proto.NewViewRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.view_ = view_;
      result.processId_ = processId_;
      if (timestampBuilder_ == null) {
        result.timestamp_ = timestamp_;
      } else {
        result.timestamp_ = timestampBuilder_.build();
      }
      if (viewChangeMessagesBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          viewChangeMessages_ = java.util.Collections.unmodifiableList(viewChangeMessages_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.viewChangeMessages_ = viewChangeMessages_;
      } else {
        result.viewChangeMessages_ = viewChangeMessagesBuilder_.build();
      }
      if (prepareMessagesBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          prepareMessages_ = java.util.Collections.unmodifiableList(prepareMessages_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.prepareMessages_ = prepareMessages_;
      } else {
        result.prepareMessages_ = prepareMessagesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.cse535.proto.NewViewRequest) {
        return mergeFrom((org.cse535.proto.NewViewRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.cse535.proto.NewViewRequest other) {
      if (other == org.cse535.proto.NewViewRequest.getDefaultInstance()) return this;
      if (other.getView() != 0) {
        setView(other.getView());
      }
      if (!other.getProcessId().isEmpty()) {
        processId_ = other.processId_;
        onChanged();
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      if (viewChangeMessagesBuilder_ == null) {
        if (!other.viewChangeMessages_.isEmpty()) {
          if (viewChangeMessages_.isEmpty()) {
            viewChangeMessages_ = other.viewChangeMessages_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureViewChangeMessagesIsMutable();
            viewChangeMessages_.addAll(other.viewChangeMessages_);
          }
          onChanged();
        }
      } else {
        if (!other.viewChangeMessages_.isEmpty()) {
          if (viewChangeMessagesBuilder_.isEmpty()) {
            viewChangeMessagesBuilder_.dispose();
            viewChangeMessagesBuilder_ = null;
            viewChangeMessages_ = other.viewChangeMessages_;
            bitField0_ = (bitField0_ & ~0x00000008);
            viewChangeMessagesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getViewChangeMessagesFieldBuilder() : null;
          } else {
            viewChangeMessagesBuilder_.addAllMessages(other.viewChangeMessages_);
          }
        }
      }
      if (prepareMessagesBuilder_ == null) {
        if (!other.prepareMessages_.isEmpty()) {
          if (prepareMessages_.isEmpty()) {
            prepareMessages_ = other.prepareMessages_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensurePrepareMessagesIsMutable();
            prepareMessages_.addAll(other.prepareMessages_);
          }
          onChanged();
        }
      } else {
        if (!other.prepareMessages_.isEmpty()) {
          if (prepareMessagesBuilder_.isEmpty()) {
            prepareMessagesBuilder_.dispose();
            prepareMessagesBuilder_ = null;
            prepareMessages_ = other.prepareMessages_;
            bitField0_ = (bitField0_ & ~0x00000010);
            prepareMessagesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPrepareMessagesFieldBuilder() : null;
          } else {
            prepareMessagesBuilder_.addAllMessages(other.prepareMessages_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.cse535.proto.NewViewRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.cse535.proto.NewViewRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int view_ ;
    /**
     * <code>int32 view = 1;</code>
     */
    public int getView() {
      return view_;
    }
    /**
     * <code>int32 view = 1;</code>
     */
    public Builder setView(int value) {
      
      view_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 view = 1;</code>
     */
    public Builder clearView() {
      
      view_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object processId_ = "";
    /**
     * <code>string processId = 2;</code>
     */
    public java.lang.String getProcessId() {
      java.lang.Object ref = processId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        processId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string processId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProcessIdBytes() {
      java.lang.Object ref = processId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        processId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string processId = 2;</code>
     */
    public Builder setProcessId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      processId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string processId = 2;</code>
     */
    public Builder clearProcessId() {
      
      processId_ = getDefaultInstance().getProcessId();
      onChanged();
      return this;
    }
    /**
     * <code>string processId = 2;</code>
     */
    public Builder setProcessIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      processId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp timestamp_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public boolean hasTimestamp() {
      return timestampBuilder_ != null || timestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
        onChanged();
      } else {
        timestampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public Builder setTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
        onChanged();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (timestamp_ != null) {
          timestamp_ =
            com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
        } else {
          timestamp_ = value;
        }
        onChanged();
      } else {
        timestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public Builder clearTimestamp() {
      if (timestampBuilder_ == null) {
        timestamp_ = null;
        onChanged();
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    private java.util.List<org.cse535.proto.ViewChangeRequest> viewChangeMessages_ =
      java.util.Collections.emptyList();
    private void ensureViewChangeMessagesIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        viewChangeMessages_ = new java.util.ArrayList<org.cse535.proto.ViewChangeRequest>(viewChangeMessages_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.cse535.proto.ViewChangeRequest, org.cse535.proto.ViewChangeRequest.Builder, org.cse535.proto.ViewChangeRequestOrBuilder> viewChangeMessagesBuilder_;

    /**
     * <code>repeated .ViewChangeRequest viewChangeMessages = 4;</code>
     */
    public java.util.List<org.cse535.proto.ViewChangeRequest> getViewChangeMessagesList() {
      if (viewChangeMessagesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(viewChangeMessages_);
      } else {
        return viewChangeMessagesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ViewChangeRequest viewChangeMessages = 4;</code>
     */
    public int getViewChangeMessagesCount() {
      if (viewChangeMessagesBuilder_ == null) {
        return viewChangeMessages_.size();
      } else {
        return viewChangeMessagesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ViewChangeRequest viewChangeMessages = 4;</code>
     */
    public org.cse535.proto.ViewChangeRequest getViewChangeMessages(int index) {
      if (viewChangeMessagesBuilder_ == null) {
        return viewChangeMessages_.get(index);
      } else {
        return viewChangeMessagesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ViewChangeRequest viewChangeMessages = 4;</code>
     */
    public Builder setViewChangeMessages(
        int index, org.cse535.proto.ViewChangeRequest value) {
      if (viewChangeMessagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureViewChangeMessagesIsMutable();
        viewChangeMessages_.set(index, value);
        onChanged();
      } else {
        viewChangeMessagesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ViewChangeRequest viewChangeMessages = 4;</code>
     */
    public Builder setViewChangeMessages(
        int index, org.cse535.proto.ViewChangeRequest.Builder builderForValue) {
      if (viewChangeMessagesBuilder_ == null) {
        ensureViewChangeMessagesIsMutable();
        viewChangeMessages_.set(index, builderForValue.build());
        onChanged();
      } else {
        viewChangeMessagesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ViewChangeRequest viewChangeMessages = 4;</code>
     */
    public Builder addViewChangeMessages(org.cse535.proto.ViewChangeRequest value) {
      if (viewChangeMessagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureViewChangeMessagesIsMutable();
        viewChangeMessages_.add(value);
        onChanged();
      } else {
        viewChangeMessagesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ViewChangeRequest viewChangeMessages = 4;</code>
     */
    public Builder addViewChangeMessages(
        int index, org.cse535.proto.ViewChangeRequest value) {
      if (viewChangeMessagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureViewChangeMessagesIsMutable();
        viewChangeMessages_.add(index, value);
        onChanged();
      } else {
        viewChangeMessagesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ViewChangeRequest viewChangeMessages = 4;</code>
     */
    public Builder addViewChangeMessages(
        org.cse535.proto.ViewChangeRequest.Builder builderForValue) {
      if (viewChangeMessagesBuilder_ == null) {
        ensureViewChangeMessagesIsMutable();
        viewChangeMessages_.add(builderForValue.build());
        onChanged();
      } else {
        viewChangeMessagesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ViewChangeRequest viewChangeMessages = 4;</code>
     */
    public Builder addViewChangeMessages(
        int index, org.cse535.proto.ViewChangeRequest.Builder builderForValue) {
      if (viewChangeMessagesBuilder_ == null) {
        ensureViewChangeMessagesIsMutable();
        viewChangeMessages_.add(index, builderForValue.build());
        onChanged();
      } else {
        viewChangeMessagesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ViewChangeRequest viewChangeMessages = 4;</code>
     */
    public Builder addAllViewChangeMessages(
        java.lang.Iterable<? extends org.cse535.proto.ViewChangeRequest> values) {
      if (viewChangeMessagesBuilder_ == null) {
        ensureViewChangeMessagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, viewChangeMessages_);
        onChanged();
      } else {
        viewChangeMessagesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ViewChangeRequest viewChangeMessages = 4;</code>
     */
    public Builder clearViewChangeMessages() {
      if (viewChangeMessagesBuilder_ == null) {
        viewChangeMessages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        viewChangeMessagesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ViewChangeRequest viewChangeMessages = 4;</code>
     */
    public Builder removeViewChangeMessages(int index) {
      if (viewChangeMessagesBuilder_ == null) {
        ensureViewChangeMessagesIsMutable();
        viewChangeMessages_.remove(index);
        onChanged();
      } else {
        viewChangeMessagesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ViewChangeRequest viewChangeMessages = 4;</code>
     */
    public org.cse535.proto.ViewChangeRequest.Builder getViewChangeMessagesBuilder(
        int index) {
      return getViewChangeMessagesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ViewChangeRequest viewChangeMessages = 4;</code>
     */
    public org.cse535.proto.ViewChangeRequestOrBuilder getViewChangeMessagesOrBuilder(
        int index) {
      if (viewChangeMessagesBuilder_ == null) {
        return viewChangeMessages_.get(index);  } else {
        return viewChangeMessagesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ViewChangeRequest viewChangeMessages = 4;</code>
     */
    public java.util.List<? extends org.cse535.proto.ViewChangeRequestOrBuilder> 
         getViewChangeMessagesOrBuilderList() {
      if (viewChangeMessagesBuilder_ != null) {
        return viewChangeMessagesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(viewChangeMessages_);
      }
    }
    /**
     * <code>repeated .ViewChangeRequest viewChangeMessages = 4;</code>
     */
    public org.cse535.proto.ViewChangeRequest.Builder addViewChangeMessagesBuilder() {
      return getViewChangeMessagesFieldBuilder().addBuilder(
          org.cse535.proto.ViewChangeRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .ViewChangeRequest viewChangeMessages = 4;</code>
     */
    public org.cse535.proto.ViewChangeRequest.Builder addViewChangeMessagesBuilder(
        int index) {
      return getViewChangeMessagesFieldBuilder().addBuilder(
          index, org.cse535.proto.ViewChangeRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .ViewChangeRequest viewChangeMessages = 4;</code>
     */
    public java.util.List<org.cse535.proto.ViewChangeRequest.Builder> 
         getViewChangeMessagesBuilderList() {
      return getViewChangeMessagesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.cse535.proto.ViewChangeRequest, org.cse535.proto.ViewChangeRequest.Builder, org.cse535.proto.ViewChangeRequestOrBuilder> 
        getViewChangeMessagesFieldBuilder() {
      if (viewChangeMessagesBuilder_ == null) {
        viewChangeMessagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.cse535.proto.ViewChangeRequest, org.cse535.proto.ViewChangeRequest.Builder, org.cse535.proto.ViewChangeRequestOrBuilder>(
                viewChangeMessages_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        viewChangeMessages_ = null;
      }
      return viewChangeMessagesBuilder_;
    }

    private java.util.List<org.cse535.proto.PrepareRequest> prepareMessages_ =
      java.util.Collections.emptyList();
    private void ensurePrepareMessagesIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        prepareMessages_ = new java.util.ArrayList<org.cse535.proto.PrepareRequest>(prepareMessages_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.cse535.proto.PrepareRequest, org.cse535.proto.PrepareRequest.Builder, org.cse535.proto.PrepareRequestOrBuilder> prepareMessagesBuilder_;

    /**
     * <code>repeated .PrepareRequest prepareMessages = 5;</code>
     */
    public java.util.List<org.cse535.proto.PrepareRequest> getPrepareMessagesList() {
      if (prepareMessagesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(prepareMessages_);
      } else {
        return prepareMessagesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PrepareRequest prepareMessages = 5;</code>
     */
    public int getPrepareMessagesCount() {
      if (prepareMessagesBuilder_ == null) {
        return prepareMessages_.size();
      } else {
        return prepareMessagesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PrepareRequest prepareMessages = 5;</code>
     */
    public org.cse535.proto.PrepareRequest getPrepareMessages(int index) {
      if (prepareMessagesBuilder_ == null) {
        return prepareMessages_.get(index);
      } else {
        return prepareMessagesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PrepareRequest prepareMessages = 5;</code>
     */
    public Builder setPrepareMessages(
        int index, org.cse535.proto.PrepareRequest value) {
      if (prepareMessagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePrepareMessagesIsMutable();
        prepareMessages_.set(index, value);
        onChanged();
      } else {
        prepareMessagesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PrepareRequest prepareMessages = 5;</code>
     */
    public Builder setPrepareMessages(
        int index, org.cse535.proto.PrepareRequest.Builder builderForValue) {
      if (prepareMessagesBuilder_ == null) {
        ensurePrepareMessagesIsMutable();
        prepareMessages_.set(index, builderForValue.build());
        onChanged();
      } else {
        prepareMessagesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PrepareRequest prepareMessages = 5;</code>
     */
    public Builder addPrepareMessages(org.cse535.proto.PrepareRequest value) {
      if (prepareMessagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePrepareMessagesIsMutable();
        prepareMessages_.add(value);
        onChanged();
      } else {
        prepareMessagesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PrepareRequest prepareMessages = 5;</code>
     */
    public Builder addPrepareMessages(
        int index, org.cse535.proto.PrepareRequest value) {
      if (prepareMessagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePrepareMessagesIsMutable();
        prepareMessages_.add(index, value);
        onChanged();
      } else {
        prepareMessagesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PrepareRequest prepareMessages = 5;</code>
     */
    public Builder addPrepareMessages(
        org.cse535.proto.PrepareRequest.Builder builderForValue) {
      if (prepareMessagesBuilder_ == null) {
        ensurePrepareMessagesIsMutable();
        prepareMessages_.add(builderForValue.build());
        onChanged();
      } else {
        prepareMessagesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PrepareRequest prepareMessages = 5;</code>
     */
    public Builder addPrepareMessages(
        int index, org.cse535.proto.PrepareRequest.Builder builderForValue) {
      if (prepareMessagesBuilder_ == null) {
        ensurePrepareMessagesIsMutable();
        prepareMessages_.add(index, builderForValue.build());
        onChanged();
      } else {
        prepareMessagesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PrepareRequest prepareMessages = 5;</code>
     */
    public Builder addAllPrepareMessages(
        java.lang.Iterable<? extends org.cse535.proto.PrepareRequest> values) {
      if (prepareMessagesBuilder_ == null) {
        ensurePrepareMessagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, prepareMessages_);
        onChanged();
      } else {
        prepareMessagesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PrepareRequest prepareMessages = 5;</code>
     */
    public Builder clearPrepareMessages() {
      if (prepareMessagesBuilder_ == null) {
        prepareMessages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        prepareMessagesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PrepareRequest prepareMessages = 5;</code>
     */
    public Builder removePrepareMessages(int index) {
      if (prepareMessagesBuilder_ == null) {
        ensurePrepareMessagesIsMutable();
        prepareMessages_.remove(index);
        onChanged();
      } else {
        prepareMessagesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PrepareRequest prepareMessages = 5;</code>
     */
    public org.cse535.proto.PrepareRequest.Builder getPrepareMessagesBuilder(
        int index) {
      return getPrepareMessagesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PrepareRequest prepareMessages = 5;</code>
     */
    public org.cse535.proto.PrepareRequestOrBuilder getPrepareMessagesOrBuilder(
        int index) {
      if (prepareMessagesBuilder_ == null) {
        return prepareMessages_.get(index);  } else {
        return prepareMessagesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PrepareRequest prepareMessages = 5;</code>
     */
    public java.util.List<? extends org.cse535.proto.PrepareRequestOrBuilder> 
         getPrepareMessagesOrBuilderList() {
      if (prepareMessagesBuilder_ != null) {
        return prepareMessagesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(prepareMessages_);
      }
    }
    /**
     * <code>repeated .PrepareRequest prepareMessages = 5;</code>
     */
    public org.cse535.proto.PrepareRequest.Builder addPrepareMessagesBuilder() {
      return getPrepareMessagesFieldBuilder().addBuilder(
          org.cse535.proto.PrepareRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .PrepareRequest prepareMessages = 5;</code>
     */
    public org.cse535.proto.PrepareRequest.Builder addPrepareMessagesBuilder(
        int index) {
      return getPrepareMessagesFieldBuilder().addBuilder(
          index, org.cse535.proto.PrepareRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .PrepareRequest prepareMessages = 5;</code>
     */
    public java.util.List<org.cse535.proto.PrepareRequest.Builder> 
         getPrepareMessagesBuilderList() {
      return getPrepareMessagesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.cse535.proto.PrepareRequest, org.cse535.proto.PrepareRequest.Builder, org.cse535.proto.PrepareRequestOrBuilder> 
        getPrepareMessagesFieldBuilder() {
      if (prepareMessagesBuilder_ == null) {
        prepareMessagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.cse535.proto.PrepareRequest, org.cse535.proto.PrepareRequest.Builder, org.cse535.proto.PrepareRequestOrBuilder>(
                prepareMessages_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        prepareMessages_ = null;
      }
      return prepareMessagesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:NewViewRequest)
  }

  // @@protoc_insertion_point(class_scope:NewViewRequest)
  private static final org.cse535.proto.NewViewRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.cse535.proto.NewViewRequest();
  }

  public static org.cse535.proto.NewViewRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NewViewRequest>
      PARSER = new com.google.protobuf.AbstractParser<NewViewRequest>() {
    @java.lang.Override
    public NewViewRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NewViewRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NewViewRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NewViewRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.cse535.proto.NewViewRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

