// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: linearpbft.proto

package org.cse535.proto;

public interface TransactionInputConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TransactionInputConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 setNumber = 1;</code>
   */
  int getSetNumber();

  /**
   * <code>.Transaction transaction = 2;</code>
   */
  boolean hasTransaction();
  /**
   * <code>.Transaction transaction = 2;</code>
   */
  org.cse535.proto.Transaction getTransaction();
  /**
   * <code>.Transaction transaction = 2;</code>
   */
  org.cse535.proto.TransactionOrBuilder getTransactionOrBuilder();

  /**
   * <code>int32 view = 3;</code>
   */
  int getView();

  /**
   * <code>repeated string serverNames = 5;</code>
   */
  java.util.List<java.lang.String>
      getServerNamesList();
  /**
   * <code>repeated string serverNames = 5;</code>
   */
  int getServerNamesCount();
  /**
   * <code>repeated string serverNames = 5;</code>
   */
  java.lang.String getServerNames(int index);
  /**
   * <code>repeated string serverNames = 5;</code>
   */
  com.google.protobuf.ByteString
      getServerNamesBytes(int index);
}
