// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: linearpbft.proto

package org.cse535.proto;

public interface TxnRelayResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TxnRelayResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>string serverName = 2;</code>
   */
  java.lang.String getServerName();
  /**
   * <code>string serverName = 2;</code>
   */
  com.google.protobuf.ByteString
      getServerNameBytes();

  /**
   * <code>int32 option = 3;</code>
   */
  int getOption();

  /**
   * <code>.ExecutionReplyRequest executionReply = 4;</code>
   */
  boolean hasExecutionReply();
  /**
   * <code>.ExecutionReplyRequest executionReply = 4;</code>
   */
  org.cse535.proto.ExecutionReplyRequest getExecutionReply();
  /**
   * <code>.ExecutionReplyRequest executionReply = 4;</code>
   */
  org.cse535.proto.ExecutionReplyRequestOrBuilder getExecutionReplyOrBuilder();
}
